# VaultChatFormatter Configuration
#
# To reload this configuration file, run `/vaultchatformatter reload`.
# (and make sure you have the 'vaultchatformatter.reload' permission)

# The chat format.
#
# The following placeholders can be used in the format, and will be replaced
# by their corresponding value when the format is applied.
#
# {prefix} ==> the players prefix
# {suffix} ==> the players suffix
# {name} ==> the players name
# {displayname} ==> the players displayname
# {message} ==> the message being sent by the player
#
# Standard Minecraft color codes can be used in the format.
format: "<{prefix}{name}{suffix}> {message}"
# Whether or not this plugin should format join and leave messages.
# {message} placeholder is not valid here.
format-join-leave: false
join-format: " > {prefix}{name}{suffix} has joined the game."
leave-format: " > {prefix}{name}{suffix} has left the game."