# VaultChatFormatter Configuration
#
# To reload this configuration file, run `/vaultchatformatter reload`.
# (and make sure you have the 'vaultchatformatter.reload' permission)

# The chat format.
#
# The following placeholders can be used in the format, and will be replaced
# by their corresponding value when the format is applied.
#
# {prefix} ==> the players prefix
# {suffix} ==> the players suffix
# {name} ==> the players name
# {displayname} ==> the players displayname
# {message} ==> the message being sent by the player
#
# Standard Minecraft color codes can be used in the format.
# This is the format for all messages sent to chat.
format: "<{prefix}{displayname}{suffix}> {message}"
# Whether or not this plugin should format join and leave messages.
# {message} placeholder is not valid here.
format-join-leave: false
join-format: " &7&l>&f {prefix}{name}{suffix}&f has joined the game."
leave-format: " &7&l>&f {prefix}{name}{suffix}&f has left the game."
# Whether or not this plugin should format player death messages.
# {message} placeholder is not valid here.
format-deaths: false
# The player name(s) will be replaced using this format.
deaths-format: "{prefix}{name}{suffix}"